export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  LOGOUT_USER: 'LOGOUT_USER',
};

export const courseConstants = {
  ADD_COURSE_REQUEST: 'ADD_COURSE_REQUEST',
  ADD_COURSE_SUCCESS: 'ADD_COURSE_SUCCESS',
  ADD_COURSE_FAILURE: 'ADD_COURSE_FAILURE',

  GET_COURSES_REQUEST: 'GET_COURSES_REQUEST',
  GET_COURSES_SUCCESS: 'GET_COURSES_SUCCESS',
  GET_COURSES_FAILURE: 'GET_COURSES_FAILURE',

  GET_COURSE_BY_SLUG: 'GET_COURSE_BY_SLUG',
};
export const themeConstants = {
  GET_THEMES_REQUEST: 'GET_THEMES_REQUEST',
  GET_THEMES_SUCCESS: 'GET_THEMES_SUCCESS',
  GET_THEMES_FAILURE: 'GET_THEMES_FAILURE',
};

export const chatConstants = {
  GET_FRIENDS_REQUEST: 'GET_FRIENDS_REQUEST',
  GET_FRIENDS_SUCCESS: 'GET_FRIENDS_SUCCESS',
  GET_FRIENDS_FAILURE: 'GET_FRIENDS_FAILURE',

  ACCESS_CHAT_REQUEST: 'ACCESS_CHAT_REQUEST',
  ACCESS_CHAT_SUCCESS: 'ACCESS_CHAT_SUCCESS',
  ACCESS_CHAT_FAILURE: 'ACCESS_CHAT_FAILURE',

  FETCH_CHAT_REQUEST: 'FETCH_CHAT_REQUEST',
  FETCH_CHAT_SUCCESS: 'FETCH_CHAT_SUCCESS',
  FETCH_CHAT_FAILURE: 'FETCH_CHAT_FAILURE',

  ACCESS_CHATBYID_REQUEST: 'ACCESS_CHATBYID_REQUEST',
  ACCESS_CHATBYID_SUCCESS: 'ACCESS_CHATBYID_SUCCESS',
  ACCESS_CHATBYID_FAILURE: 'ACCESS_CHATBYID_FAILURE',

  CREATE_GROUP_REQUEST: 'CREATE_GROUP_REQUEST',
  CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
  CREATE_GROUP_FAILURE: 'CREATE_GROUP_FAILURE',

  UPDATE_GROUP_NAME_REQUEST: 'UPDATE_GROUP_NAME_REQUEST',
  UPDATE_GROUP_NAME_SUCCESS: 'UPDATE_GROUP_NAME_SUCCESS',
  UPDATE_GROUP_NAME_FAILURE: 'UPDATE_GROUP_NAME_FAILURE',

  ADD_USER_REQUEST: 'ADD_USER_REQUEST',
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  ADD_USER_FAILURE: 'ADD_USER_FAILURE',

  REMOVE_USER_REQUEST: 'REMOVE_USER_REQUEST',
  REMOVE_USER_SUCCESS: 'REMOVE_USER_SUCCESS',
  REMOVE_USER_FAILURE: 'REMOVE_USER_FAILURE',

  SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',

  GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
  GET_MESSAGES_FAILURE: 'GET_MESSAGES_FAILURE',
};
